usr/share/opencv/doc/*          usr/share/doc/opencv-doc/
usr/share/opencv/haarcascades   usr/share/doc/opencv-doc/examples/haarcascades
usr/share/opencv/lbpcascades    usr/share/doc/opencv-doc/examples/lbpcascades
usr/share/opencv/samples/*      usr/share/doc/opencv-doc/examples/
samples/python                  usr/share/doc/opencv-doc/examples/
debian/samples/c/Makefile.debian usr/share/doc/opencv-doc/examples/c/
